// components/Footer.vue
<template>
    <footer class="py-sm-5 p-3 bg-secondary">

       <main class="container">
            <main class=" row align-items-center flex-column-reverse flex-sm-row">
            
           <div class="col-sm">
                <div class="row">
                <div class="col-sm ">
                    <p class="fw-900 text-primary d-none d-sm-block">ABOUT</p>
                    <ul class="nav flex-sm-column justify-content-center">
                        <li class="nav-item " v-for="(item, index) in about" :key="index">
                            <a :href="item.link" class="nav-link ps-0 text-light">
                                {{item.text}}
                            </a>
                        </li>
                    </ul>
                </div>

                 <div class="col-sm ">
                    <p class="fw-900 text-primary d-none d-sm-block">HELP</p>
                    <ul class="nav flex-sm-column justify-content-center">
                        <li class="nav-item " v-for="(item, index) in help" :key="index">
                            <a :href="item.link" class="nav-link ps-0 text-light">
                                {{item.text}}
                            </a>
                        </li>
                    </ul>
                </div>

            </div>
           </div>

            <div class="col-sm-8 d-flex">
               <div class="ms-auto  me-auto me-sm-0">
                    <div class="mx-auto " >
                        <a href="#" class="navbar-brand d-flex ">
                            <span class="me-2"><img src="~/static/icon2.png" width="30px" alt=""></span>
                            <h2 class="text-light fw-700 ">Liguidity Finance</h2>
                        </a>
                    </div>
                    <ul class="nav ">
                                    <li class="nav-item" v-for="(item, index) in soc_media" :key="index">
                                        <a :href="item.link" class="text-muted nav-link">
                                            <i :class="`fab fa-${item.icon} fa-lg `"></i>
                                        </a>
                                    </li>
                    </ul>
               </div>
            </div>

        </main>
       </main>
    
        <hr>
       <main class=" container px-0 d-flex justify-content-between ">
             
            <div class="d-flex align-items-center">



               <div class="me-2 me-sm-4 d-flex align-items-center">
                    <label class="switch mx-2">
                   <i class="fas fa-moon text-muted"></i>

                        <input type="checkbox" >
                        <span class="slider round"></span>
                     <i class="fas fa-sun text-warning"></i>

                    </label>
               </div>


                <div>
                    <span class="text-muted">
                        <i class="fas fa-globe "></i> 
                        <span class="fw-700">EN</span>
                    </span>
                </div>


                

            </div>


            <div class="d-flex align-items-center pe-sm-5 me-sm-5">
                <div class="me-2 me-sm-4">
                    <img src="~/assets/img/lfi.png" width="20px" alt="">
                    <span class="text-muted small te">$0.00001</span>
                </div>
                <div>
                    <button class="btn btn-primary">
                        <span>BY LFI</span>
                        <i class="fas fa-long-arrow-alt-right btn-sm"></i>
                    </button>
                </div>
            </div>



       </main>
    </footer>
</template>
<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
    data(){
        return {
            about: [
                {text: "Contact", link: "financeliquidity@gmail.com"},
                {text: "Brand", link: "#"},
                {text: "Blog", link: "https://medium.com/@financeliquidity"},
                {text: "Community", link: "https://t.me/liquidityfinanc"},
            ],
            help: [
                {text: "Support", link: "#"},
                {text: "Guides", link: "https://medium.com/@financeliquidity"},
                {text: "Partnership", link: "financeliquidity@gmail.com"},
            ],
            soc_media: [
                {link: "https://twitter.com/LIQUIDITFINANCE", icon: "twitter" },
                {link: "https://web.facebook.com/LiquidityFinance-214111300634295", icon: "facebook" },
                {link: "#", icon: "instagram" },
                {link: "https://t.me/liquidityfinanc", icon: "telegram" },
                {link: "#", icon: "github" }
            ]
        }
        }
    
})
</script>


<style>
/* The switch - the box around the slider */
.switch {
  position: relative;
  display: flex;
  justify-content: space-evenly;
  padding: 0px 3px;
  align-items: center;
  width: 60px;
  height: 34px;
}



/* Hide default HTML checkbox */
.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

.switch i {
    z-index: 3000;
}

/* The slider */
.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(255,255,255,0.1);
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background-color: #071229;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: rgb(243, 165, 8, 0.2);
}



input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>

// src/components/shared/Footer/index.tsx
import React from "react";
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="bg-grey_70 px-4 py-20 md:px-16 md:py-24 font-head text-white">
      <div className="w-full mx-auto">
        <div className="flex flex-col md:flex-row">
          <div className="flex flex-col-reverse justify-between md:w-full md:flex-row">
            <div className="w-full md:w-4/6 md:flex justify-between flex-wrap">
              <div className="flex justify-between w-full md:w-2/5 mb-10 md:mb-0">
                <div className="company">
                  <h2 className=" text-primary font-bold mb-3">ABOUT US</h2>
                  <ul>
                    <li className="mb-2">
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Contact Us
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Brand
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Blog
                      </a>
                    </li>
                    <li>
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Community
                      </a>
                    </li>
                  </ul>
                </div>
                <div className="pricing">
                  <h2 className=" text-primary font-bold mb-3">ABOUT US</h2>
                  <ul>
                    <li className="mb-2">
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Contact Us
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Brand
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Blog
                      </a>
                    </li>
                    <li>
                      <a href="#" className="text-sm text-grey_20 font-bold">
                        Community
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="others md:w-1/3 w-full">
                <h2 className=" text-primary font-bold mb-3">ABOUT US</h2>
                <ul>
                  <li className="mb-2">
                    <a href="#" className="text-sm text-grey_20 font-bold">
                      Contact Us
                    </a>
                  </li>
                  <li className="mb-2">
                    <a href="#" className="text-sm text-grey_20 font-bold">
                      Brand
                    </a>
                  </li>
                  <li className="mb-2">
                    <a href="#" className="text-sm text-grey_20 font-bold">
                      Blog
                    </a>
                  </li>
                  <li>
                    <a href="#" className="text-sm text-grey_20 font-bold">
                      Community
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="mb-10 md:mb-0 w-full md:w-2/6">
              <div className="flex items-center">
                <img src="/assets/images/lfi-small.svg" alt="..." />
                <span className="ml-2 font-bold text-2xl">
                  Liquidity Finance
                </span>
              </div>
            </div>
          </div>
        </div>
        <ul className="social mt-8 mb-6 flex">
          <li className="mr-6">
            <a href="#" className=" font-normal">
              <img src="/assets/icons/twitter.svg" alt="twitter" />
            </a>
          </li>
          <li className="mr-6">
            <a href="#" className="">
              <img src="/assets/icons/telegram.svg" alt="telegram" />
            </a>
          </li>
          <li className="mr-6">
            <a href="#" className="">
              <img src="/assets/icons/facebook.svg" alt="facebook" />
            </a>
          </li>
          <li className="mr-6">
            <a href="#" className="">
              <img src="/assets/icons/instagram.svg" alt="instagram" />
            </a>
          </li>
          <li className="mr-6">
            <a href="#" className="">
              <img src="/assets/icons/discord.svg" alt="discord" />
            </a>
          </li>
          <li className="">
            <a href="#" className="">
              <img src="/assets/icons/linkedin.svg" alt="linkedin" />
            </a>
          </li>
        </ul>

        <hr />

        <div className="mt-7 flex flex-col justify-between items-start md:items-center md:flex-row">
          <div className="flex items-center mb-4 md:mb-0">
            <div
              className="
    relative
    inline-block
    w-10
    mr-2
    align-middle
    select-none
    transition
    duration-200
    ease-in
  "
            >
              <input
                type="checkbox"
                name="toggle"
                id="toggle"
                className="
      toggle-checkbox
      absolute
      block
      w-6
      h-6
      rounded-full
      bg-white
      border-4
      appearance-none
      cursor-pointer
    "
              />
              <label
                htmlFor="toggle"
                className="
      toggle-label
      block
      overflow-hidden
      h-6
      rounded-full
      bg-gray-300
      cursor-pointer
    "
              ></label>
            </div>
            <div className="ml-10 flex items-center">
              <img src="/assets/icons/global.svg" alt="lang" />
              <span className="font-bold text-sm text-grey_20 ml-2">EN</span>
            </div>
          </div>
          <div className="flex items-center">
            <div className="flex items-center mr-6">
              <img src="/assets/icons/lfi-32.png" alt="..." />
              <span className="text-sm font-bold text-grey_20 ml-2">
                $0.00001
              </span>
            </div>
            <Link href="/#app">
              <a className="btn-primary text-white font-bold py-2 px-4 rounded-lg flex items-center">
                Buy LFI
                <img
                  src="/assets/icons/arrow-right.svg"
                  alt="..."
                  className="ml-2.5"
                />
              </a>
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}
